### PR TITLE
Symfoni pr update

### LINKED ISSUE #6: Migrate to `@typechain/hardhat`
https://github.com/symfoni/symfoni-monorepo/blob/fc0722089528ca02d0330ebdb66beba4e8e9f76c/packages/hardhat-react/src/index.ts#L8

`hardhat-typechain` has been deprecated and moved to https://www.npmjs.com/package/@typechain/hardhat.

This package should point to that.

### PR DESCRIPTION
**Pull request by asheliahut**
This is to update the dependencies to work with latest typechain..
This also updates default Solidity to 0.8.4 for the fixtures.

Fixes #6

### CODE REVIEW

**Comment by asheliahut** [comment]
@RobertoSnap Feel free to take anything you want. I have tested all of this and created a fork for my work in the meantime with these updates.
https://github.com/asheliahut/symfoni-monorepo

**Comment by asheliahut** [comment]
Any word on looking at this PR?

**Comment by RobertoSnap** [comment]
@asheliahut  Sorry for late reply! Awesome that you have created a PR, i will look at it ASAP and get back to you.  Hopefully during the weekend.

**Comment by asheliahut** [comment]
@RobertoSnap any word? That must be a long weekend yall have overseas 😆 j/k Just wanted to bump again after a week.

**Comment by RobertoSnap** [comment]
🙈🙈🙈🙈🙈🙈🙈

**Comment by RobertoSnap** [comment]
A bit overworked atm, hopefully soon (™️)🙈

**Comment by asheliahut** [comment]
I'm sure the work I did here is already outdated 😂 probably still a good stepping stone towards updating fully now though.

**Pull request closed without merging**
